# Site settings
author: Tanesha Goodman
title: Back To School: Extreme Adult Edition
header-img: img/home-bg.png
email: t24good@icloud.com
copyright_name: Tanesha Goodman
description: > # this means to ignore newlines until "baseurl:"
  BTS
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: tgoodyyy
github_username:  t24good

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
